version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    networks:
      - myappNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot service
  springboot-app:
    image: mahmoud085/tp-foyer:1.0.0
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    networks:
      - myappNetwork

networks:
  myappNetwork:

volumes:
  mysql-data: