version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-foyer:
    build: ./
    ##image: mhamed/tp-foyer:1.0.0
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8089:8089"

    stdin_open: true
    tty: true

volumes:
  db: